project:
  type: website

website:
  title: "Sophie Nguyen"
  #navbar:
    #left:
      #- href: index.qmd
        #text: Home
      #- productivity/intro.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto

